### PR TITLE
Ported old frontend to new backend

### LINKED ISSUE #68: Migrate admin portal to new backend
The following sub-features should be migrated:
- [x] User creation
- [x] User modification
- [x] User deletion
- [x] Organization proposals
- [x] Organization profile details

### LINKED ISSUE #71: Clicking approve or reject doesn't update UI
We have to refresh to update the UI at the moment.

### LINKED ISSUE #75: Repair approve / disapprove header bar
The header bar for approving and disapproving a report should work as intended.

### LINKED ISSUE #76: It should not be possible to submit a report for review (after rejection) when nothing was changed
This causes state change errors.

### LINKED ISSUE #77: A user should not be able to select himself as reviewer

### LINKED ISSUE #78: Pagination
The report pagination does not work anymore and should also be migrated.

### LINKED ISSUE #79: Extract user role from jwt token
Current token role function does not work properly.

### LINKED ISSUE #80: Organization modification fails for some properties
The admin panel for our organization details doesn't always want to update. The culprit seems to be `homeAddressNumber`.

### LINKED ISSUE #88: Create organization response from 200 to 204
Update expected result code in frontend after merge

### LINKED ISSUE #89: Frontend non-admin should only get bare minimum information about other organizations (--> ContractorDto)
The current `OrganizationController` should **only** perform operations with regards to the organization of the currently signed in user. We should use the `ContractorController` to return these minified details about an organization.

Perhaps a name-change is at place here.

### PR DESCRIPTION
**Pull request by tabeckers**
This PR addresses the porting of the old frontend to the new backend. Since our API has changed quite a bit, many changes were necessary. The following issues will be closed with this pull request:
Fixes #78 
Fixes #80 
Fixes #79 
Fixes #68 
Fixes #75 
Fixes #71 
Fixes #76 
Fixes #77 
Fixes #88
Fixes #89

### CODE REVIEW

File: src/api/auth.js [hunk 1]
```diff
@@ -4,11 +4,11 @@ import axios from '@/utils/axios'
 export default { 
   login: ({ email, password }) => {
     return axios.post(
-      '/api/authentication/signin', 
+      '/api/auth/signin/',
```
Comment (yorickdewid) [inline src/api/auth.js]: No trailing slash

File: src/api/auth.js [hunk 2]
```diff
@@ -4,11 +4,11 @@ import axios from '@/utils/axios'
...
   login: ({ email, password }) => {
     return axios.post(
-      '/api/authentication/signin', 
+      '/api/auth/signin/', 
       { email, password }
     )
   },
   refresh: () => {
-    return axios.get('/api/authentication/refresh')
+    return axios.get('/api/auth/token-refresh/')
```
Comment (yorickdewid) [inline src/api/auth.js]: No trailing slash

File: src/api/address.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
+import axios from '../utils/axios'
+
+export default {
+    /**
+     * Lists all address suggestions for a given query.
+     * @param query The query string.
+     */
+    getAddressSuggestions(query: string) {
+        return axios.get(`/api/address/suggest?query=${query}`); // TODO Limit?
```
Comment (yorickdewid) [inline src/api/address.ts]:
```suggestion
        return axios.get(`/api/address/suggest?query=${query}&limit=10`); // TODO Limit?
```

File: src/api/org.js [hunk 4]
```diff
@@ -2,26 +2,71 @@
...
+   */
+  getOrganizationById: ({ id }) => {
+    return axios.get(`/api/admin/organization/${id}`)
+  },
+
+  /**
+   * Admin call for getting all existing organizations.
+   */
+  getAllOrganizations: () => {
+    return axios.get('/api/admin/organization/')
```
Comment (yorickdewid) [inline src/api/org.js:23]: Trailing slash

File: src/components/atoms/review/ReportUserRole.vue [hunk 5]
```diff
@@ -1,4 +1,6 @@
 <template>
+  <div>
+    <h3>This is the debug version of ReportUserRole.vue</h3>
```
Comment (yorickdewid) [inline src/components/atoms/review/ReportUserRole.vue]: ?

File: src/components/atoms/review/ReportUserRole.vue [hunk 6]
```diff
@@ -27,12 +33,19 @@ export default {
       'areReviewersAvailable'
     ]),
     userObject() {
+
+      console.log('ReportUserRole this.user', this.user)
```
Comment (yorickdewid) [inline src/components/atoms/review/ReportUserRole.vue]: Remove all log

File: src/components/molecules/OrganizationProposalLine.vue [hunk 7]
```diff
@@ -38,9 +38,15 @@ export default {
   },
   computed: {
     tokenLink() {
-      let host = process.env.VUE_APP_API_BASE_URL || ''
+      // TODO Is this the way to go?
+      let host = window.location.origin || ''
+      
+      // Quick fix for http --> https
+      host = host.replace(/^http:\/\//i, 'https://');
```
Comment (yorickdewid) [inline src/components/molecules/OrganizationProposalLine.vue]: Why? There is only always HTTPS

File: src/components/molecules/UploadArea.vue [hunk 8]
```diff
@@ -78,14 +80,17 @@ export default {
      * Start the creation of a new report once the upload has finished with success
      */
     handleSuccess(file, response) {
-      if (file && this.$refs.dropzone) {
-        this.$refs.dropzone.removeFile(file)
-      }
+      // TODO Why do we need this?
```
Comment (yorickdewid) [inline src/components/molecules/UploadArea.vue:83]: Good question, ask @pnobbe

File: src/components/organisms/CreateProposalModal.vue [hunk 9]
```diff
@@ -112,7 +112,9 @@ export default {
             this.isDisabled = false
             this.enableAllFields()
             this.clearAllFieldValues()
-            this.$refs.form.resetValidation()
+
+            // TODO I belive we don't need this
+            //this.$refs.form.resetValidation()
```
Comment (yorickdewid) [inline src/components/organisms/CreateProposalModal.vue:117]: Ask @pnobbe

File: src/components/organisms/SampleDataEditor.vue [hunk 10]
```diff
@@ -510,7 +521,8 @@ export default {
         this.$emit("stored", { success: false, message: err });
       }
     },
-    handleError() {
+    handleError(err) {
+      console.log('err', err)
```
Comment (yorickdewid) [inline src/components/organisms/SampleDataEditor.vue]: rm

File: src/config/roles.js [hunk 11]
```diff
@@ -1,8 +1,20 @@
...
+export const userRolesToInteger = [
+  { value: 'Superuser', number: 0 },
+  { value: 'Verifier', number: 1 },
+  { value: 'Writer', number: 2 },
+  { value: 'Reader', number: 3 }
+]
+
+export function userRoleToInteger({ roleAsEnumText }) {
+  return userRolesToInteger.find(x => x.value === roleAsEnumText).number;
+}
```
Comment (yorickdewid) [inline src/config/roles.js]: LF

File: src/models/Address.ts [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+    this.city = city;
+  }
+
+  format() : string {
+    return `${this.street} ${this.buildingNumberCleaned()}, ${this.postalCode} ${this.city}`
+  }
+
+  buildingNumberCleaned() : string {
+
+    console
```
Comment (yorickdewid) [inline src/models/Address.ts]: ?

File: src/models/Address.ts [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+
+    return this.buildingNumber.trim();
+  }
+}
+
+export default AddressModel;
```
Comment (yorickdewid) [inline src/models/Address.ts:36]: You can export and define the class in once. Matter of preference.

File: src/router/index.ts [hunk 14]
```diff
@@ -109,26 +109,26 @@ const routes = [
   // Report
   {
     path: '/report/create/',
```
Comment (yorickdewid) [inline src/router/index.ts]: report -> inquiry

File: src/views/report/Step3.vue [hunk 15]
```diff
@@ -91,19 +91,23 @@ export default {
...
           id: report.id,
-          document: report.documentId
+          fileName: report.fileName
         }
       };
     }
   },
   async created() {
+
+    console.log('Step3 this.activeReport', this.activeReport)
```
Comment (yorickdewid) [inline src/views/report/Step3.vue]: rm

File: src/views/report/Step2.vue [hunk 16]
```diff
@@ -200,9 +208,14 @@ export default {
     ]),
     handleAddSample() {
       this.countdownToNewSample = this.samples.length
+
+      console.log('handleAddSample this.countdownToNewSample', this.countdownToNewSample)
```
Comment (yorickdewid) [inline src/views/report/Step2.vue]: rm

File: src/views/Map.vue [hunk 17]
```diff
@@ -115,24 +115,52 @@ export default {
...
-          layout: {
-            visibility: this.getLayerVisibility({ layer })
-          },
-          paint: {
-            "fill-color": ["get", "color"],
-            "fill-opacity": 0.8
-          }
-        });
+
+      console.log('Arrived at AddLayersToMapbox')
```
Comment (yorickdewid) [inline src/views/Map.vue]: rm

File: src/views/Map.vue [hunk 18]
```diff
@@ -115,24 +115,52 @@ export default {
...
+      //     layout: {
+      //       visibility: this.getLayerVisibility({ layer })
+      //     },
+      //     paint: {
+      //       "fill-color": ["get", "color"],
+      //       "fill-opacity": 0.8
+      //     }
+      //   });
+      // });
+      this.$store.map.addSource('mapillary', {
```
Comment (yorickdewid) [inline src/views/Map.vue]: disable

**Review by yorickdewid — COMMENTED** [review]
Glanced over a lot of things, but then this is just a workable solution, not a definitive one

File: src/components/atoms/review/ReportUserRole.vue (hunk 5 above)
Comment (tabeckers) [reply src/components/atoms/review/ReportUserRole.vue]: Was a debug work in progress, I re-implemented this class in `ReportUserRoleExplicit` and forgot to remove these old debug tags since this component isn't being used anymore.

File: src/components/molecules/OrganizationProposalLine.vue (hunk 7 above)
Comment (tabeckers) [reply src/components/molecules/OrganizationProposalLine.vue]: When the app is deployed this is true. During the development process we spotted a `http` call together and concluded that this had to be changed into `https`. I'll remove it again.

**Review by yorickdewid — APPROVED** [review]

File: src/components/organisms/CreateProposalModal.vue (hunk 9 above)
Comment (pnobbe) [reply src/components/organisms/CreateProposalModal.vue:117]: I believe this simply removes any input field highlighting that might remain even after the values have been programatically reset. It would need to be tested with and without the line active to confirm.

File: src/components/molecules/UploadArea.vue (hunk 8 above)
Comment (pnobbe) [reply src/components/molecules/UploadArea.vue:83]: I think this simply removes all files from the dropzone after a succesful submit to reset the dropzone instance for new use. If it doesn't get reused we don't need this.
